---
  - name: Test Task
    win_ping:
    register: ping_result
  
  - name: Debug
    debug:        
        var: ping_result
  
  - name: Create folder
    win_file:
        path: c:\data_from_ansible
        state: directory 

  - name: Copy Secret file
    win_copy:
        src: some.secret.file.txt
        dest: c:\data_from_ansible\
  
  - name: Setup IIS 
    include_tasks: setup_iis.yml

